URL = 'https://www.epam.com/'
ABOUT_URL = 'https://www.epam.com/about'
BROWSER = 'Chrome'
COOKIE_BUTTON = 'css=#onetrust-accept-btn-handler'
LANGUAGE_LOCATOR = 'xpath=/html/body/div/div[2]/div[2]/div[1]/header/div/div/ul/li[2]/div/div/button/span/div'
PAGE_TITLE = 'title:EPAM | Software Engineering & Product Development Services'
SERVICES_LOCATOR = 'link=Services'
INDUSTRIES_LOCATOR = 'link=Industries'
INSIGHTS_LOCATOR = 'link=Insights'
ABOUT_LOCATOR = 'link=About'
CAREERS_LOCATOR = 'link=Careers'
MENU_LOCATORS = [SERVICES_LOCATOR, INDUSTRIES_LOCATOR, INSIGHTS_LOCATOR, ABOUT_LOCATOR, CAREERS_LOCATOR]
SEARCH_ICON = 'css=.header-search__button'
SEARCH_FORM = 'css=#new_form_search'
SEARCH_BUTTON = 'css=.custom-button'
SEARCH_RESULTS_PAGE = 'https://www.epam.com/search?q=Python'
SEARCH_RESULTS_LOCATOR = 'xpath=//*[@id="main"]/div[1]/div/section/div[2]/div[4]/section/h2'
EXPECTED_RESULT = '10 RESULTS FOR "PYTHON"'